### ISSUE TITLE
Исправить ссылку на скачивание в манифесте

### ISSUE THREAD

**Issue by effrit** [Septdir/com_updateserver#2]
Если не создан пункт меню для компонента, то выдаваемая ссылка ломает инсталляторы расширений.

**Comment by Septdir** [comment]
А подробнее?

**Comment by effrit** [comment]
Если ставишь по дефолту компонент, не создавая для него пункта меню, то для добавляемых расширений получается громоздкая ссылка с параметрами. 
Вставляешь её в xml и админка при заходе на расширение падает.

Т.е. я добавил свой плагинчик, добавил версию, взял ссылку и вставил в плагин.
При попытке зайти в настройки плагина стала вываливаться 500-я ошибка. На 4-ой альфе - то же самое. После создания пункта меню все стало ОК.

**Comment by Septdir** [comment]
Можешь логи глянуть что за ошибка, чтобы уже наверняка закрыть

А то единственное в чем вижу разницу это в слеше.

Без пункта меню
`component/updateserver/?task=download`

С пунктом меню
`update?task=download`

Можно еще декодировать url чтобы ссылки были без "спец символов"

**Comment by effrit** [comment]
Блин, косячу.
Cсылку вставил из файла манифеста, а не ссылку на манифест )).

**Comment by Septdir** [comment]
@effrit Но ссылку все рано надо поправить. А то не комильфо.

**Comment by Septdir** [comment]
Готово, Добавил в релиз [1.1.0](https://github.com/Septdir/com_updateserver/releases/tag/1.1.0)
