### ISSUE TITLE
Предложение: добавить постоянную ссылку на последнюю версию расширения

### ISSUE THREAD

**Issue by effrit** [Septdir/com_updateserver#3]
Было бы удобно, если бы компонент по ссылке без параметра версии выдавал последнюю версию расширения. Т.е, чтобы можно было размещать ссылку на скачивание расширений, которая была бы всегда актуальной.

**Comment by Septdir** [comment]
В понедельник сделаю. Но тогда будет выдаваться последняя стабильная версия.

**Comment by effrit** [comment]
Да, так норм будет.

**Comment by Septdir** [comment]
Готово, Добавил в релиз [1.1.0](https://github.com/Septdir/com_updateserver/releases/tag/1.1.0)

**Comment by effrit** [comment]
ага, ужо обновился на тестовом, пасиб.
а на форуме чего не рекламируешься?

**Comment by Septdir** [comment]
Ну так сложилось, что нет особого желания рекламировать свои расширения на joomlaforum.
А так само расширение много где есть даже в  [JED ](https://extensions.joomla.org/extension/update-server/) добавил.

**Comment by effrit** [comment]
Ну так ты же торжественно вернулся )).
Да и вообще, нефиг сраться, и так уже скоро битриксоиды и вп-шники одолеют нас.

Кстати, ещё одно предложение функционала - сделать фронт с выводом списка расширений и ссылками на последние стабильные релизы, раз уже она работает.
а то щас с фронта 500 ошибку выдает - не солидон.
типа репозиторий для ленивых, типа меня )

**Comment by Septdir** [comment]
>Кстати, ещё одно предложение функционала - сделать фронт с выводом списка расширений и ссылками на последние стабильные релизы, раз уже она работает.

Нет такого не будет, у меня было расширение, которое именно каталог расширений с сервером, навороченной мультиязчностью и т.д 
Если хочешь поищу в архивах, но оно очень тяжелое.

А данное расширение именно простой сервер обновлений, я его вообще делал чтобы удобно было с альфы на беты и на релиз легко расширения перекидывать.
